#!/usr/bin/env python3
"""
Interactive table for ltl2asp_ext.asp: every formula, every trace, both semantics.

The formulas, traces and reference evaluator live in
`tests/test_semantics/ltlf_ext_harness.py`, so this script and the pytest suite
cannot drift apart. Add a formula there and it appears in both.

    conda activate arm_env
    python files/until_semantics/ltlf_testkit.py           # the table
    python files/until_semantics/ltlf_testkit.py --prev    # + the Y/Z formulas
    python files/until_semantics/ltlf_testkit.py --diff    # only the rows where
                                                           # strong and weak differ
    python files/until_semantics/ltlf_testkit.py --emit    # write generated_cases.asp

For the same checks as assertions instead of a table:

    python -m pytest tests/test_semantics/test_ltlf_asp_ext.py -q
"""
from __future__ import annotations

import argparse
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, REPO)

from tests.test_semantics.ltlf_ext_harness import (  # noqa: E402
    FORMULAS, PREV_FORMULAS, TRACES, emit_formula, emit_trace, pretty,
    sat_ref, sat_set_from_clingo,
)

HERE = os.path.dirname(os.path.abspath(__file__))


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--prev", action="store_true", help="include the Y/Z formulas")
    ap.add_argument("--diff", action="store_true",
                    help="only rows where strong and weak disagree")
    ap.add_argument("--emit", action="store_true", help="write generated_cases.asp")
    args = ap.parse_args(argv)

    formulas = dict(FORMULAS)
    if args.prev:
        formulas.update(PREV_FORMULAS)

    print(f"{'formula':26} {'trace':13} {'trace shape':26} {'strong':>8} {'weak':>8}")
    mismatches = rows = 0
    for label, f in formulas.items():
        strong_set = sat_set_from_clingo(f, TRACES, False, args.prev)
        weak_set = sat_set_from_clingo(f, TRACES, True, args.prev)
        for name, trace in TRACES.items():
            s_got, w_got = name in strong_set, name in weak_set
            s_exp = sat_ref(f, trace, 0, False)
            w_exp = sat_ref(f, trace, 0, True)
            mismatches += (s_got != s_exp) + (w_got != w_exp)
            if args.diff and s_got == w_got:
                continue
            rows += 1
            mark = lambda got, exp: ("SAT" if got else "-") + ("" if got == exp else "!")
            print(f"{label:26} {name:13} {pretty(trace):26} "
                  f"{mark(s_got, s_exp):>8} {mark(w_got, w_exp):>8}")
        if not args.diff:
            print()

    print(f"\n{rows} rows, {mismatches} disagreements with the reference evaluator")
    if args.emit:
        out = os.path.join(HERE, "generated_cases.asp")
        with open(out, "w") as fh:
            fh.write("% Generated by files/until_semantics/ltlf_testkit.py --emit\n")
            for label, f in formulas.items():
                facts, _ = emit_formula(f)
                fh.write(f"\n% Formula {label}\n" + "\n".join(facts) + "\n")
            for name, trace in TRACES.items():
                fh.write(f"\n% Trace {pretty(trace)}\n"
                         + "\n".join(emit_trace(name, trace)) + "\n")
        print(f"wrote {out}")
    return 1 if mismatches else 0


if __name__ == "__main__":
    raise SystemExit(main())
