"""
Violation traces generated by running a real controller.

Split in two. The pure parts - trace formatting, candidate enumeration, target
selection - are tested directly and run everywhere. The end-to-end generation
needs Spectra to synthesise a controller and clingo to decide what a trace
violates, so those tests are marked and skipped when the tools are missing.

The two integration tests worth reading first are the regressions, because both
bugs produced *plausible* output rather than an error:

* A refused step used to abandon the episode. Spectra's controller simply will
  not accept an input its assumptions forbid, and the executor does not advance
  when it refuses - so retrying is free, and giving up instead threw away most
  attempts.
* A refusal during the rogue phase used to end the search. It is in fact the
  violation: the controller is only obliged to respond while the environment
  keeps its assumptions. Treating it as failure produced traces for minepump
  alone, whose controller happens to tolerate the violating input and carry on,
  while every other case study silently produced nothing.
"""
import os
import random
import shutil
import unittest
from unittest.mock import patch

from spec_repair.diagnosis import controller_trace_generation as ctg
from spec_repair.diagnosis.controller_trace_generation import (
    ControllerTraceError, generate_controller_violation_trace,
    violatable_assumptions)
from spec_repair.model.spectra_specification import SpectraSpecification

CASE_STUDIES = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
    "input-files", "case-studies", "spectra", "case_study_2")

MINEPUMP = os.path.join(CASE_STUDIES, "minepump", "original.spectra")
ARBITER = os.path.join(CASE_STUDIES, "arbiter", "original.spectra")
TRAFFIC = os.path.join(CASE_STUDIES, "traffic_updated", "original.spectra")

TOOLS_AVAILABLE = shutil.which("clingo") is not None


class TestTraceFormatting(unittest.TestCase):
    def test_states_render_in_the_form_the_repair_reads(self):
        lines = ctg._trace_lines(
            [{"a": "true", "b": "false"}, {"a": "false", "b": "true"}],
            ["a", "b"], "trace_name_0")
        text = "".join(lines)
        self.assertIn("holds_at(a,0,trace_name_0).", text)
        self.assertIn("not_holds_at(b,0,trace_name_0).", text)
        self.assertIn("not_holds_at(a,1,trace_name_0).", text)
        self.assertIn("holds_at(b,1,trace_name_0).", text)

    def test_timepoints_are_separated_by_a_blank_line(self):
        """The repair's parser reads a trace as blank-line-delimited states."""
        lines = ctg._trace_lines([{"a": "true"}, {"a": "true"}], ["a"], "t")
        self.assertEqual(2, sum(1 for line in lines if line.strip() == ""))

    def test_a_variable_missing_from_a_state_is_false(self):
        """
        The controller reports only what it knows about; anything absent is
        false rather than omitted, since a trace with a hole in it is not a
        trace.
        """
        lines = ctg._trace_lines([{"a": "true"}], ["a", "b"], "t")
        self.assertIn("not_holds_at(b,0,t).", "".join(lines))


class TestCandidateInputs(unittest.TestCase):
    def test_a_small_space_is_enumerated_exhaustively(self):
        domains = {"x": ["false", "true"], "y": ["false", "true"]}
        candidates = ctg._candidate_inputs(domains, random.Random(0))
        self.assertEqual(4, len(candidates))
        self.assertEqual(4, len({tuple(sorted(c.items())) for c in candidates}))

    def test_a_large_space_is_sampled_rather_than_built(self):
        """2^20 candidates is not worth constructing to pick one from."""
        domains = {f"v{i}": ["false", "true"] for i in range(20)}
        candidates = ctg._candidate_inputs(domains, random.Random(0))
        self.assertEqual(ctg.MAX_CANDIDATES_PER_STEP, len(candidates))

    def test_the_same_seed_gives_the_same_candidates(self):
        """Generation is reproducible or it is not evidence."""
        domains = {f"v{i}": ["false", "true"] for i in range(20)}
        first = ctg._candidate_inputs(domains, random.Random(7))
        second = ctg._candidate_inputs(domains, random.Random(7))
        self.assertEqual(first, second)


class TestTargetSelection(unittest.TestCase):
    """
    Which input the rogue environment picks, given what each would violate.

    The violation oracle is stubbed: this is about the preference order, not
    about whether the ASP encoding is right.
    """

    DOMAINS = {"x": ["false", "true"]}

    def _pick(self, violations_by_x, targets):
        def fake(spec, states, candidate, variables, repairable, trace_name):
            return set(violations_by_x[candidate["x"]])
        with patch.object(ctg, "_hypothetical_violations", fake):
            return ctg._targeted_input(None, [], self.DOMAINS, ["x"],
                                       {"A", "B"}, targets, random.Random(0), "t")

    def test_an_input_breaking_exactly_the_target_is_chosen(self):
        chosen = self._pick({"true": ["A"], "false": []}, {"A"})
        self.assertEqual({"x": "true"}, chosen)

    def test_an_input_breaking_a_non_target_is_never_chosen(self):
        """
        The methodological point: a real environment fails in one way at a
        time, and a trace that breaks assumptions nobody aimed at tells the
        repair nothing about which weakening is wanted.
        """
        chosen = self._pick({"true": ["B"], "false": []}, {"A"})
        self.assertEqual({"x": "false"}, chosen, "picked an off-target violation")

    def test_a_harmless_input_is_preferred_to_an_off_target_one(self):
        chosen = self._pick({"true": ["A", "B"], "false": []}, {"A"})
        self.assertEqual({"x": "false"}, chosen)

    def test_none_when_every_candidate_would_overshoot(self):
        """Abandon the episode rather than record more violations than asked."""
        self.assertIsNone(self._pick({"true": ["B"], "false": ["B"]}, {"A"}))


class TestViolatableAssumptions(unittest.TestCase):
    def test_only_non_initial_assumptions_are_offered(self):
        """
        Initial assumptions are excluded deliberately: weakening one drags
        system variables in, which Spectra rejects, and it changes which states
        the system may start in rather than answering the repair question.
        """
        names = violatable_assumptions(MINEPUMP)
        self.assertEqual(["assumption1_1", "assumption2_1"], names)
        self.assertNotIn("initial_assumption", names)

    def test_guarantees_are_not_offered(self):
        spec = SpectraSpecification.from_file(MINEPUMP)
        guarantees = set(spec.filter(lambda x: x["name"].str.startswith("guarantee"))["name"])
        self.assertTrue(guarantees, "minepump should have guarantees to exclude")
        self.assertFalse(set(violatable_assumptions(MINEPUMP)) & guarantees)


@unittest.skipUnless(TOOLS_AVAILABLE, "clingo is not installed")
class TestGenerationEndToEnd(unittest.TestCase):
    """Synthesises a real controller and runs it. Slow, and needs the toolchain."""

    def test_a_trace_violates_exactly_one_assumption(self):
        _, violated = generate_controller_violation_trace(
            MINEPUMP, seed=0, attempts=6, max_random_steps=30)
        self.assertEqual(1, len(violated), f"expected one violation, got {violated}")

    def test_the_requested_assumption_is_among_those_violated(self):
        """
        The target must break. It no longer has to break *alone*.

        Requiring it to be the only one made the target unreachable wherever
        assumptions overlap: the step that reaches the state where the intended
        assumption can break may be a step that breaks another on the way, and
        rejecting those left some assumptions with no trace at all. Everything
        violated is recorded, so the repair still knows what it was handed.
        """
        for target in violatable_assumptions(MINEPUMP):
            with self.subTest(target=target):
                _, violated = generate_controller_violation_trace(
                    MINEPUMP, seed=0, attempts=6, max_random_steps=30,
                    target_assumptions=[target])
                self.assertIn(target, violated)

    def test_the_same_seed_gives_the_same_trace(self):
        """
        Reproducibility, which this did not have until the controller's choice
        was pinned.

        The seed always governed every choice *this* code makes, and synthesis
        is deterministic - two syntheses of minepump hash identically. The
        traces still differed run to run, across separate processes and in
        length, because the controller has freedom: it usually has several legal
        responses to an input, and `ControllerExecutor` picked among them
        itself, differently each time.

        `FlexibleControllerExecutor` hands that decision back - it waits after
        each step, offers the successor states through `getChoices()`, and
        advances only on `chooseNextState()`. Sorting those into a canonical
        order and drawing with the run's seeded generator makes the whole trace
        a function of the seed.
        """
        first, first_violated = generate_controller_violation_trace(
            MINEPUMP, seed=3, attempts=6, max_random_steps=30)
        second, second_violated = generate_controller_violation_trace(
            MINEPUMP, seed=3, attempts=6, max_random_steps=30)
        self.assertEqual(first, second)
        self.assertEqual(first_violated, second_violated)

    def test_different_seeds_still_explore_differently(self):
        """
        Pinning the choice must not collapse the traces into one. Drawing the
        controller's move with the seeded generator - rather than always taking
        the first - keeps five traces worth generating.
        """
        traces = set()
        for seed in range(5):
            lines, _ = generate_controller_violation_trace(
                MINEPUMP, seed=seed, attempts=6, max_random_steps=30)
            traces.add("".join(lines))
        self.assertGreater(len(traces), 1, "every seed produced the same trace")

    def test_different_seeds_reach_different_assumptions(self):
        """
        Coverage is the point of generating five traces. Five breaking the same
        assumption exercise one weakening five times; five breaking five
        exercise five.
        """
        reached = set()
        for seed in range(5):
            try:
                _, violated = generate_controller_violation_trace(
                    TRAFFIC, seed=seed, attempts=6, max_random_steps=30,
                    target_assumptions=[violatable_assumptions(TRAFFIC)[seed % 4]])
                reached.update(violated)
            except ControllerTraceError:
                continue
        self.assertGreater(len(reached), 1, f"only reached {reached}")

    def test_a_liveness_only_specification_is_refused_not_faked(self):
        """
        arbiter's only assumption is `GF(a)`, which no finite prefix can
        violate. The generator must say so rather than return a trace that
        violates nothing - shipping one of those is what made 8 of 81 case
        studies fail unrecognisably on 2026-08-06.
        """
        with self.assertRaises(ControllerTraceError):
            generate_controller_violation_trace(
                ARBITER, seed=0, attempts=3, max_random_steps=15)

    def test_the_system_half_of_the_trace_is_controller_output(self):
        """
        The reason this setup exists. Every state must assign every variable,
        system ones included, and those values come from the controller rather
        than from a solver free to pick anything the specification allows.
        """
        lines, _ = generate_controller_violation_trace(
            MINEPUMP, seed=0, attempts=6, max_random_steps=30)
        spec = SpectraSpecification.from_file(MINEPUMP)
        variables = ctg._spec_variable_names(spec)
        states = [b for b in "".join(lines).strip().split("\n\n") if b.strip()]
        for i, state in enumerate(states):
            for var in variables:
                self.assertIn(f"holds_at({var},{i},", state,
                              f"{var} missing from timepoint {i}")


if __name__ == "__main__":
    unittest.main()
